#!/usr/bin/bash
# Copyright (C) 2015 Marco Melletti
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

TAGLIST="/home/mello/fotoprova/.tags"

usage(){
	echo
	echo `basename $0`" - find images based on tag metadata in exif comments"
	echo 
	echo `basename $0`" [-a|-o] tags [basedir]"
	echo `basename $0`" -l"
	echo 
	echo "OPTIONS"
	echo -e "\t-a"
	echo -e "\t\tall tags must be present in each result (default behavior)"
	echo -e "\t-o"
	echo -e "\t\tat least one of the tags must be present in each result"
	echo -e "\t-l"
	echo -e "\t\tlist all present tags"
	echo
	echo "'tags' is a comma-separated list of tags to search for"
	echo
	echo "if 'basedir' is specified, files will be searched starting from that directory instead of current working directory."
	echo
	echo
	exit 0
}

listTags(){
	cat "$TAGLIST" | rev | sed -e 's/^[0-9]*\t//' | rev | sed -e "s/{//" | sed -e "s/}//" | sort | less
}

# $1: search mode (OR|AND)
# $2: internal representation tag string ({tag1}{tag2}..)
findTag(){
	m="$1"
	tags="$2"
	count="$3"
	for f in *; do
		if test -d "$f"; then
			pushd "$f" &> /dev/null
			findTag	"$m" "$tags" "$count"
			popd &> /dev/null
		else
			ft=`phototag get -i "$f"`
			echo "$tags" | (found=0; while read t; do if [[ $ft = *$t* ]]; then found=$((found+1)); fi; done; if test \( "$found" -eq "$count" -a "$m" = "AND" \) -o \( "$found" -gt 0 -a "$m" = "OR" \); then echo `pwd`/"$f"; fi)
		fi
	done
}

if test $# -lt 1; then
	usage
fi

basedir=`pwd`
mode="AND"

case $1 in
	"-l")
		listTags
		exit 0
	;;
	"-a")
		shift
	;;
	"-o")
		mode="OR"
		shift
	;;
	"-*")
		usage
	;;
esac

if test -d "$2"; then
	basedir="$2"
else
	usage
fi

tags=`tagstocomment "$1" | sed -e 's/}/}\\n/g' | sed -e '/^$/d'`
tagcount=`echo "$tags" | wc -l`

pushd basedir &> /dev/null

findTag "$mode" "$tags" "$tagcount" 

popd &> /dev/null
